# .github/workflows/github-action-workflow_call-01.yml
# github-action-workflow_call.ymlì„ í˜¸ì¶œí•˜ëŠ” íŒŒì¼

name: Workflows Names - github-action-workflow_call-01
run-name: Runs Names - github-action-workflow_call-01 ğŸš€
on: 
  workflow_dispatch

jobs:
  Jobs-Names-github-action-workflow_call-01:
    uses: ./github-action-workflow_call.yml
    with:
      environment: production
